package ua.ukrainedrones

object Strings {
    fun get(lang: AppLanguage): StringSet = when (lang) {
        AppLanguage.UA -> UA
        AppLanguage.EN -> EN
    }

    data class StringSet(
        val appTitle: String,
        val officialAlertBanner: String,
        val settingsTitle: String,
        val settingsButton: String,
        val backButton: String,
        val languageLabel: String,
        val languageChooseTitle: String,
        val languageChooseLater: String,
        val okButton: String,
        val onboardingTipsTitle: String,
        val onboardingTipTap: String,
        val onboardingTipSettings: String,
        val onboardingTipSiren: String,
        val zonesLabel: String,
        val redZoneLabel: String,
        val yellowZoneLabel: String,
        val alertsLabel: String,
        val redZoneAlertsTitle: String,
        val redZoneAlertsDesc: String,
        val yellowZoneAlertsTitle: String,
        val yellowZoneAlertsDesc: String,
        val fastAlertsSoonerTitle: String,
        val fastAlertsSoonerDesc: String,
        val officialAlertsTitle: String,
        val officialAlertsDesc: String,
        val officialAlertsRedTridentNote: String,
        val sirenOverrideTitle: String,
        val sirenOverrideDesc: String,
        val allAlertsOffLabel: String,
        val zoneButtonRed: String,
        val zoneButtonYellow: String,
        val redZoneHint: String,
        val yellowZoneHint: String,
        val zoneExplain: String,
        val threatsLabel: String,
        val threatMapLabel: String,
        val threatAlertLabel: String,
        val fastGroupLabel: String,
        val slowGroupLabel: String,
        val disclaimerTitle: String,
        val disclaimerBody: String,
        val exitButton: String,
        val redZoneAlert: String,
        val yellowZoneAlert: String,
        val notifOngoingTitle: String,
        val notifChannelName: String,
        val notifChannelDesc: String,
        val notifStatusZones: String,
        val notifBodyRegion: String,
        val attributionText: String,
        val madeBy: String,
        val connOnline: String,
        val connOffline: String,
        val connServerLine: String,
        val connUpLine: String,
        val connDownLine: String,
        val connBackup: String,
        val connStatusTitle: String,
        val connNeptunLabel: String,
        val connBackupLabel: String,
        val connEffectiveFormat: String,
        val connActiveLabel: String,
        val connForceOfflineTitle: String,
        val connBackupNoMapDesc: String,
        val attributionBackup: String,
        val reliabilityLow: String,
        val reliabilityMedium: String,
        val reliabilityHigh: String,
        val reliabilityUnknown: String,
        val speedUnit: String,
        val groupLabel: String,
        val uncertaintyLabel: String,
        val noRegion: String,
        val minutesAgoSuffix: String,
        val justNow: String,
        val hoursAgoSuffix: String,
        val daysAgoSuffix: String,
        val mixedTimeFormat: String,
        val noThreatsMessage: String,
        val updateAvailableTitle: String,
        val updateVersionLabel: String,
        val updateNotesTitle: String,
        val updateDownload: String,
        val updateDownloading: String,
        val updateInstall: String,
        val updateLater: String,
        val updateRetry: String,
        val updateFailedTitle: String,
        val updateInstallPermissionTitle: String,
        val updateInstallPermissionBody: String,
        val updateOpenSettings: String,
        val updateReadyToInstallTitle: String,
        val updateReadyToInstallBody: String,
        val updateUpToDate: String,
        val updateCheckFailed: String,
        val checkForUpdates: String,
        val updateButton: String,
        val updateAvailableButton: String,
        val advisoryLabel: String,
        val areaOnlyLabel: String,
        val cardSkullNote: String,
        val distanceLabel: String,
        val distanceToCityFormat: String,
        val etaLabel: String,
        val etaUnit: String,
        val approxNote: String,
        val pillDistanceCd: String,
        val gpsOffLabel: String,
        val inRedZone: String,
        val inYellowZone: String,
        val outsideZones: String,
        val editZonesLabel: String,
        val alertsBellToggle: String,
        val kmUnit: String,
        val meterUnit: String,
        val moreInfoLabel: String,
        val offLabel: String,
        val mapCenterLabel: String,
        val followMeTitle: String,
        val followMeDesc: String,
        val pinCityTitle: String,
        val pinCityDesc: String,
        val mapPillPinned: String,
        val alertBannerFormat: String,
        val alertSourceBackup: String,
        val alertSourceBoth: String,
        val notifBodyRegionFormat: String,
        val notifStatusPinned: String,
        val offlineStatusTitle: String,
        val offlineBodyFormat: String,
        val offlineOfficialSirensLine: String,
        val offlineRetryAction: String,
        val offlineDurMinFormat: String,
        val offlineChannelName: String,
        val offlineChannelDesc: String,
        val offlineUiFormat: String,
        val allClearTitle: String,
        val allClearText: String,
        val batteryTitle: String,
        val batteryBody: String,
        val batteryAllowButton: String,
        val batteryGranted: String,
        val cardSizeLabel: String,
        val guideTitle: String,
        val guideSettingsButton: String,
        val guideCategoryMap: String,
        val guideCategoryZones: String,
        val guideCategoryLocation: String,
        val guideCategoryCards: String,
        val guideCategorySettings: String,
        val guideLiveTitle: String,
        val guideLiveSummary: String,
        val guideLiveD1: String,
        val guideLiveD2: String,
        val guideLiveD3: String,
        val guideStripTitle: String,
        val guideStripSummary: String,
        val guideStripD1: String,
        val guideStripD2: String,
        val guideStripD3: String,
        val guideConnTitle: String,
        val guideConnSummary: String,
        val guideConnD1: String,
        val guideConnD2: String,
        val guideConnD3: String,
        val guideZonesTitle: String,
        val guideZonesSummary: String,
        val guideZonesD1: String,
        val guideZonesD2: String,
        val guideZonesD3: String,
        val guideEditZonesTitle: String,
        val guideEditZonesSummary: String,
        val guideEditZonesD1: String,
        val guideEditZonesD2: String,
        val guideEditZonesD3: String,
        val guideNotifTitle: String,
        val guideNotifSummary: String,
        val guideNotifD1: String,
        val guideNotifD2: String,
        val guideNotifD3: String,
        val guideFastTitle: String,
        val guideFastSummary: String,
        val guideFastD1: String,
        val guideFastD2: String,
        val guideFastD3: String,
        val guideFollowTitle: String,
        val guideFollowSummary: String,
        val guideFollowD1: String,
        val guideFollowD2: String,
        val guideFollowD3: String,
        val guidePinTitle: String,
        val guidePinSummary: String,
        val guidePinD1: String,
        val guidePinD2: String,
        val guidePinD3: String,
        val guideCardSizeTitle: String,
        val guideCardSizeSummary: String,
        val guideCardSizeD1: String,
        val guideCardSizeD2: String,
        val guideCardSizeD3: String,
        val guideCardReadTitle: String,
        val guideCardReadSummary: String,
        val guideCardReadD1: String,
        val guideCardReadD2: String,
        val guideCardReadD3: String,
        val guideLangTitle: String,
        val guideLangSummary: String,
        val guideLangD1: String,
        val guideLangD2: String,
        val guideLangD3: String,
        val guideTogglesTitle: String,
        val guideTogglesSummary: String,
        val guideTogglesD1: String,
        val guideTogglesD2: String,
        val guideTogglesD3: String,
        val guideUpdateTitle: String,
        val guideUpdateSummary: String,
        val guideUpdateD1: String,
        val guideUpdateD2: String,
        val guideUpdateD3: String
    )

    private val UA = StringSet(
        appTitle = "Українські дрони",
        officialAlertBanner = "Одеса: тривога",
        settingsTitle = "Налаштування",
        settingsButton = "Налаштування",
        backButton = "Назад",
        languageLabel = "Мова",
        languageChooseTitle = "Оберіть мову",
        languageChooseLater = "Пізніше",
        okButton = "ОК",
        onboardingTipsTitle = "Кілька підказок",
        onboardingTipTap = "Натисни будь-який дрон на мапі, щоб відкрити його картку.",
        onboardingTipSettings = "У Налаштуваннях (шестерня) — зони тривог, мова та путівник по функціях.",
        onboardingTipSiren = "Сирена за замовчуванням слідує за режимом звуку телефона — увімкни «Сирена звучить завжди», щоб змінити.",
        zonesLabel = "Зони тривог",
        redZoneLabel = "Червона зона",
        yellowZoneLabel = "Жовта зона",
        alertsLabel = "Оповіщення",
        redZoneAlertsTitle = "Оповіщення червоної зони",
        redZoneAlertsDesc = "Сирена при загрозі в червоній зоні.",
        yellowZoneAlertsTitle = "Оповіщення жовтої зони",
        yellowZoneAlertsDesc = "Попереджувальний звук при загрозі в жовтій зоні.",
        fastAlertsSoonerTitle = "Швидкі об'єкти сповіщають раніше",
        fastAlertsSoonerDesc = "Ракети (балістика, крилаті, КАБ, МіГ-31К) піднімають сирену, щойно перетинають будь-яку межу зони.",
        officialAlertsTitle = "Офіційні сповіщення",
        officialAlertsDesc = "Сповіщення про офіційну повітряну тривогу в області. Не впливає на червону/жовту зони.",
        sirenOverrideTitle = "Сирена звучить завжди",
        sirenOverrideDesc = "Сигнал тривоги звучить, навіть коли телефон у вібро- чи беззвучному режимі. За замовчуванням вимкнено — звук слідує за налаштуваннями телефону.",
        officialAlertsRedTridentNote = "Червоний тризуб у шапці означає, що офіційна тривога активна.",
        zoneButtonRed = "Червона зона: натисни, щоб наблизити, утримуй — налаштування",
        zoneButtonYellow = "Жовта зона: натисни, щоб наблизити, утримуй — налаштування",
        redZoneHint = "Радіус критичної зони навколо тебе — 1–5 км.",
        yellowZoneHint = "Радіус попереджувальної зони — 6–20 км.",
        zoneExplain = "Зони слідують за твоїм GPS-положенням. Загроза в червоній зоні — червоний банер і сирена; у жовтій — жовтий банер і звук попередження. Швидкі об'єкти (ракети) можуть сповіщати сиреною відразу на вході в будь-яку зону. Координати загроз грубі, тож межі зон — лише орієнтир.",
        threatsLabel = "Загрози — натисни, щоб увімкнути",
        threatMapLabel = "Мапа",
        threatAlertLabel = "Сповіщення",
        fastGroupLabel = "Швидкі",
        slowGroupLabel = "Повільні",
        disclaimerTitle = "Офіційні сигнали головні",
        disclaimerBody = "Завжди керуйся офіційними сигналами повітряної тривоги. Наш застосунок використовує дані, які противник не транслює точно, — координати та відстані не можуть бути точними, навіть коли позначені як підтверджені. Показник рівня загрози — груба оцінка, а не офіційний рейтинг. Все це лише орієнтир.",
        exitButton = "Зупинити моніторинг і вийти",
        redZoneAlert = "Червона зона: тривога",
        yellowZoneAlert = "Жовта зона: тривога",
        notifOngoingTitle = "Моніторинг тривог",
        notifChannelName = "Фоновий статус",
        notifChannelDesc = "Моніторинг працює у фоновому режимі. Вимкнення цього лише приховує статусне сповіщення — сповіщення про повітряну тривогу все одно спрацьовуватимуть.",
        notifStatusZones = "Зони слідують за твоїм GPS",
        notifBodyRegion = "Одеський регіон",
        attributionText = "Карта повітряних тривог — NEPTUN",
        madeBy = "Зроблено Presaince",
        connOnline = "Онлайн",
        connOffline = "Офлайн",
        connServerLine = "З'єднання з сервером повітряних тривог NEPTUN.",
        connUpLine = "Дані оновлюються.",
        connDownLine = "З'єднання втрачено, дані можуть бути застарілими.",
        connBackup = "резерв",
        connStatusTitle = "Статус системи",
        connNeptunLabel = "NEPTUN",
        connBackupLabel = "alerts.com.ua",
        connEffectiveFormat = "Зараз працює: %1\$s",
        connActiveLabel = "Активне",
        connForceOfflineTitle = "Тест: імітувати офлайн NEPTUN",
        connBackupNoMapDesc = "Резервне джерело працює лише на рівні областей — без живої карти позицій, лише статус повітряних тривог.",
        attributionBackup = "Повітряні тривоги — alerts.com.ua",
        reliabilityLow = "Достовірність: Низька",
        reliabilityMedium = "Достовірність: Середня",
        reliabilityHigh = "Достовірність: Висока",
        reliabilityUnknown = "Достовірність: Невідома",
        speedUnit = "км/год",
        groupLabel = "Хвиля",
        uncertaintyLabel = "Точність",
        noRegion = "Одеська область",
        minutesAgoSuffix = "хв тому",
        justNow = "щойно",
        hoursAgoSuffix = "год тому",
        daysAgoSuffix = "дн тому",
        mixedTimeFormat = "%1\$d год %2\$d хв тому",
        noThreatsMessage = "Загроз немає — йди на свіже повітря",
        updateAvailableTitle = "Доступна нова версія",
        updateVersionLabel = "Версія",
        updateNotesTitle = "Що нового",
        updateDownload = "Завантажити",
        updateDownloading = "Завантаження… %1\$d%%",
        updateInstall = "Встановити",
        updateLater = "Пізніше",
        updateRetry = "Спробувати знову",
        updateFailedTitle = "Не вдалося завантажити оновлення",
        updateInstallPermissionTitle = "Дозвіл на встановлення",
        updateInstallPermissionBody = "Щоб встановити оновлення, дозволь цьому застосунку встановлювати інші застосунки.",
        updateOpenSettings = "Відкрити налаштування",
        updateReadyToInstallTitle = "Оновлення готове",
        updateReadyToInstallBody = "Оновлення завантажено. Натисни «Встановити», щоб застосувати.",
        updateUpToDate = "У вас остання версія",
        updateCheckFailed = "Не вдалося перевірити оновлення",
        checkForUpdates = "Перевірити оновлення",
        updateButton = "Оновити",
        updateAvailableButton = "Доступне оновлення",
        advisoryLabel = "Спостереження",
        areaOnlyLabel = "Лише область (без точної точки)",
        cardSkullNote = "Череп (0–10) — груба оцінка: тип, відстань, достовірність, джерела. Не офіційний рейтинг і не гарантія вашої безпеки.",
        distanceLabel = "Відстань",
        distanceToCityFormat = "Відстань до %1\$s",
        etaLabel = "Час підльоту",
        etaUnit = "хв",
        approxNote = "Усі числа в застосунку приблизні",
        pillDistanceCd = "Відстань до %1\$s: %2\$d км",
        gpsOffLabel = "GPS вимкнено — зональні дані недоступні",
        inRedZone = "У червоній зоні",
        inYellowZone = "У жовтій зоні",
        outsideZones = "Поза зонами тривог",
        editZonesLabel = "Змінити зони",
        alertsBellToggle = "Увімкнути або вимкнути оповіщення",
        kmUnit = "км",
        meterUnit = "м",
        moreInfoLabel = "Детальніше",
        offLabel = "ВИМК",
        allAlertsOffLabel = "Усі сповіщення вимкнено",
        mapCenterLabel = "Центр карти",
        followMeTitle = "Слідувати за мною",
        followMeDesc = "Карта та зони слідують за твоїм GPS-положенням.",
        pinCityTitle = "Прикріпити до міста",
        pinCityDesc = "Центр карти та зони закріплюються за вибраним містом. Червоним позначені області з офіційною тривогою.",
        mapPillPinned = "Прикріплено: %1\$s",
        alertBannerFormat = "%1\$s: тривога",
        alertSourceBackup = " · резервне джерело",
        alertSourceBoth = " · NEPTUN + резервне джерело",
        notifBodyRegionFormat = "%1\$s область",
        notifStatusPinned = "Зони закріплені за містом",
        offlineStatusTitle = "Офлайн",
        offlineBodyFormat = "Офлайн %1\$s — резервні системи працюють, але менш надійні. Натисни, щоб повторити.",
        offlineOfficialSirensLine = "Покладайся на офіційні сирени.",
        offlineRetryAction = "Повторити",
        offlineDurMinFormat = "%1\$d хв",
        offlineChannelName = "Офлайн-моніторинг",
        offlineChannelDesc = "Повідомлення, коли з'єднання із сервером тривог втрачено.",
        offlineUiFormat = "Офлайн %1\$s",
        allClearTitle = "%1\$s: відбій тривоги",
        allClearText = "Офіційна повітряна тривога завершилася. Все спокійно.",
        batteryTitle = "Тривоги мають лунати завжди",
        batteryBody = "Android може зупиняти застосунок у фоні, щоб економити заряд. Сам застосунок споживає дуже мало енергії — живі сповіщення приходять миттєво, а ваше місцезнаходження визначається економно. Тож дозвіл працювати у фоні не розряджатиме телефон, а тривоги лунатимуть без перешкод. Безпека понад усе.",
        batteryAllowButton = "Дозволити у фоні",
        batteryGranted = "Без обмежень у фоні",
        cardSizeLabel = "Розмір і деталізація картки загрози",
        guideTitle = "Путівник по функціях",
        guideSettingsButton = "Путівник по функціях",
        guideCategoryMap = "Карта",
        guideCategoryZones = "Зони та тривоги",
        guideCategoryLocation = "Місцезнаходження",
        guideCategoryCards = "Картка загрози",
        guideCategorySettings = "Налаштування",
        guideLiveTitle = "Жива мапа загроз",
        guideLiveSummary = "Жива мапа всіх відстежуваних загроз по всій країні.",
        guideLiveD1 = "Маркери показують усі 8 типів загроз — дрони, ракети, КАБ та інше.",
        guideLiveD2 = "Під час тривоги мапа розширюється, щоб бачити інші регіони.",
        guideLiveD3 = "Натисни маркер, щоб відкрити картку; натисни порожню мапу, щоб закрити.",
        guideStripTitle = "Рядок загроз",
        guideStripSummary = "Смуга внизу — живий лічильник загроз за типами.",
        guideStripD1 = "У смузі лише типи, які зараз є поруч — кожна плитка показує живу кількість.",
        guideStripD2 = "Тип без загроз не показується; коли порожньо все — «Загроз немає».",
        guideStripD3 = "Вимкнений у Налаштуваннях тип з'являється тьмяним (сірим).",
        guideConnTitle = "Зв'язок і шкала",
        guideConnSummary = "Пілюля зверху — зв'язок із сервером тривог; шкала — відстані.",
        guideConnD1 = "Онлайн — дані оновлюються; Офлайн — дані можуть бути застарілі.",
        guideConnD2 = "Натисни пілюлю, щоб побачити статус сервера та джерело NEPTUN.",
        guideConnD3 = "Шкала масштабу в кутку показує реальні відстані на мапі.",
        guideZonesTitle = "Червона та жовта зони",
        guideZonesSummary = "Два кільця безпеки навколо тебе — термінове червоне і попереджувальне жовте.",
        guideZonesD1 = "Червона (1–5 км): загроза тут — сирена і червоний банер.",
        guideZonesD2 = "Жовта (6–20 км): загроза тут — попереджувальний звук і жовтий банер.",
        guideZonesD3 = "Натисни кнопку зони на мапі, щоб наблизитися до неї.",
        guideEditZonesTitle = "Змінити зони",
        guideEditZonesSummary = "Налаштуй радіус кожної зони та вимкни оповіщення.",
        guideEditZonesD1 = "Повзунки оновлюють кола на мапі одразу.",
        guideEditZonesD2 = "Дзвіночок вмикає чи вимикає оповіщення зони.",
        guideEditZonesD3 = "Зміни застосовуються одразу і зберігаються.",
        guideNotifTitle = "Сповіщення",
        guideNotifSummary = "Застосунок слухає у фоні та сповіщає про зони.",
        guideNotifD1 = "Червона зона — сирена; жовта — звук попередження; офіційна тривога — свій звук.",
        guideNotifD2 = "Тихий статус-запис показує, що моніторинг працює.",
        guideNotifD3 = "Моніторинг триває, навіть коли застосунок закрито.",
        guideFastTitle = "Перемикачі тривог",
        guideFastSummary = "Два перемикачі керують агресивністю сповіщень.",
        guideFastD1 = "Швидкі об'єкти раніше: ракети піднімають сирену на вході в будь-яку зону.",
        guideFastD2 = "Офіційні сповіщення: додає сигнал повітряної тривоги області.",
        guideFastD3 = "Обидва — у Налаштуваннях → Оповіщення.",
        guideFollowTitle = "Слідувати за мною",
        guideFollowSummary = "Мапа та обидві зони слідують за твоїм GPS.",
        guideFollowD1 = "Твоє положення — синя точка, що світиться.",
        guideFollowD2 = "Зони рухаються разом із тобою, тож ти завжди знаєш, чи загроза поруч.",
        guideFollowD3 = "Перемикач — у Налаштуваннях → Центр карти.",
        guidePinTitle = "Прикріпити до міста",
        guidePinSummary = "Закріпи мапу та зони за вибраним містом замість GPS.",
        guidePinD1 = "Зручно, коли стежиш за рідними в іншому місті.",
        guidePinD2 = "Відстань на картках міряється до цього міста, а не до тебе.",
        guidePinD3 = "Міста з офіційною тривогою позначені червоним.",
        guideCardSizeTitle = "Розмір картки",
        guideCardSizeSummary = "Три розміри керують деталізацією картки загрози.",
        guideCardSizeD1 = "Мала — один рядок: череп, тип і час підльоту.",
        guideCardSizeD2 = "Середня — додає відстань, швидкість і достовірність.",
        guideCardSizeD3 = "Велика — все, включно з курсом і точністю.",
        guideCardReadTitle = "Як читати картку",
        guideCardReadSummary = "Картка загрози — коротке досьє на один об'єкт.",
        guideCardReadD1 = "Шкала-череп (0–10) — груба оцінка рівня загрози.",
        guideCardReadD2 = "Відстань і час підльоту — від твого положення (або прикріпленого міста).",
        guideCardReadD3 = "Швидкість, хвиля, достовірність, точність і час фіксації — решта.",
        guideLangTitle = "Мова",
        guideLangSummary = "Перемикайся між українською та англійською будь-коли.",
        guideLangD1 = "Два прапори вгорі Налаштувань.",
        guideLangD2 = "Діє всюди — мапа, картки, сповіщення, цей гід.",
        guideLangD3 = "Вибрана мова зберігається для наступних запусків.",
        guideTogglesTitle = "Перемикачі типів загроз",
        guideTogglesSummary = "У кожного з 8 типів загроз — окремі перемикачі «Мапа» та «Сповіщення».",
        guideTogglesD1 = "Вимкнення «Мапи» ховає тип з мапи та замовчує його тривоги. Вимкнення «Сповіщень» лишає тип на мапі, але тьмяним.",
        guideTogglesD2 = "Тип з вимкненими «Сповіщеннями» чи «Мапою» не показується в смузі загроз.",
        guideTogglesD3 = "У кожній картці — деталі, типова швидкість і фото з вікі.",
        guideUpdateTitle = "Оновлення",
        guideUpdateSummary = "Застосунок перевіряє оновлення щодня та може оновитися сам.",
        guideUpdateD1 = "Нова версія показує список «Що нового».",
        guideUpdateD2 = "Завантажуй і встановлюй просто з діалогу.",
        guideUpdateD3 = "Можна також натиснути «Перевірити оновлення» в Налаштуваннях.",
    )

    private val EN = StringSet(
        appTitle = "Ukraine Drones",
        officialAlertBanner = "Odesa: alert",
        settingsTitle = "Settings",
        settingsButton = "Settings",
        backButton = "Back",
        languageLabel = "Language",
        languageChooseTitle = "Choose language",
        languageChooseLater = "Later",
        okButton = "OK",
        onboardingTipsTitle = "A few tips",
        onboardingTipTap = "Tap any drone on the map to open its details card.",
        onboardingTipSettings = "Settings (gear icon) holds alert zones, language and the feature guide.",
        onboardingTipSiren = "Sirens follow your phone's sound mode by default — turn on \"Sirens always sound\" to change it.",
        zonesLabel = "Alert zones",
        redZoneLabel = "Red zone",
        yellowZoneLabel = "Yellow zone",
        alertsLabel = "Alerts",
        redZoneAlertsTitle = "Red zone alerts",
        redZoneAlertsDesc = "Siren for threats in the red zone.",
        yellowZoneAlertsTitle = "Yellow zone alerts",
        yellowZoneAlertsDesc = "Warning chime for threats in the yellow zone.",
        fastAlertsSoonerTitle = "Fast objects alert sooner",
        fastAlertsSoonerDesc = "Missiles (ballistic, cruise, guided bombs, MiG-31K) sound the siren the moment they cross any zone boundary.",
        officialAlertsTitle = "Official alerts",
        officialAlertsDesc = "Alerts for the official oblast air-raid signal. Does not affect your Red/Yellow zone alerts.",
        sirenOverrideTitle = "Sirens always sound",
        sirenOverrideDesc = "Ring the siren even when the phone is on vibrate or silent. Off by default — alerts follow your phone's sound settings.",
        officialAlertsRedTridentNote = "A red trident in the header means the official alert is on.",
        zoneButtonRed = "Red zone: tap to zoom in, long-press for settings",
        zoneButtonYellow = "Yellow zone: tap to zoom in, long-press for settings",
        redZoneHint = "Radius of the critical zone around you — 1–5 km.",
        yellowZoneHint = "Radius of the warning zone — 6–20 km.",
        zoneExplain = "The zones follow your GPS position. A threat in the red zone — red banner and siren; in the yellow zone — amber banner and warning chime. Fast objects (missiles) may sound the siren as soon as they cross any zone boundary. Threat positions are coarse, so zone edges are only a guide.",
        threatsLabel = "Threats — tap to toggle",
        threatMapLabel = "Map",
        threatAlertLabel = "Alerts",
        fastGroupLabel = "Fast",
        slowGroupLabel = "Slow",
        disclaimerTitle = "Official signals come first",
        disclaimerBody = "Always follow official air-raid signals. Our app uses data the enemy isn't broadcasting precisely — positions and distances can't be accurate, even when marked confirmed. The threat level is a rough estimate, not an official rating. Treat everything as a rough guide only.",
        exitButton = "Stop Monitoring & Exit",
        redZoneAlert = "Red zone: alert",
        yellowZoneAlert = "Yellow zone: alert",
        notifOngoingTitle = "Alert monitoring",
        notifChannelName = "Background status",
        notifChannelDesc = "Monitoring runs in the background. Turning this off only hides this status notification — air-raid alerts still sound.",
        notifStatusZones = "Zones follow your GPS",
        notifBodyRegion = "Odesa region",
        attributionText = "Air threat map — NEPTUN",
        madeBy = "Made by Presaince",
        connOnline = "Online",
        connOffline = "Offline",
        connServerLine = "Connection to the NEPTUN air-threat server.",
        connUpLine = "Data is updating live.",
        connDownLine = "Connection lost; data may be stale.",
        connBackup = "backup",
        connStatusTitle = "System status",
        connNeptunLabel = "NEPTUN",
        connBackupLabel = "alerts.com.ua",
        connEffectiveFormat = "Currently on: %1\$s",
        connActiveLabel = "Active",
        connForceOfflineTitle = "Test: simulate NEPTUN offline",
        connBackupNoMapDesc = "The backup is oblast-level only — no live map positions, just air-raid alert status.",
        attributionBackup = "Air threat alerts — alerts.com.ua",
        reliabilityLow = "Reliability: Low",
        reliabilityMedium = "Reliability: Average",
        reliabilityHigh = "Reliability: High",
        reliabilityUnknown = "Reliability: Unknown",
        speedUnit = "km/h",
        groupLabel = "Wave size",
        uncertaintyLabel = "Precision",
        noRegion = "Odesa region",
        minutesAgoSuffix = "min ago",
        justNow = "just now",
        hoursAgoSuffix = "h ago",
        daysAgoSuffix = "d ago",
        mixedTimeFormat = "%1\$d h %2\$d min ago",
        noThreatsMessage = "No threats — go touch grass",
        updateAvailableTitle = "New version available",
        updateVersionLabel = "Version",
        updateNotesTitle = "What's new",
        updateDownload = "Download",
        updateDownloading = "Downloading… %1\$d%%",
        updateInstall = "Install",
        updateLater = "Later",
        updateRetry = "Try again",
        updateFailedTitle = "Failed to download update",
        updateInstallPermissionTitle = "Install permission",
        updateInstallPermissionBody = "To install the update, allow this app to install other apps.",
        updateOpenSettings = "Open settings",
        updateReadyToInstallTitle = "Update ready",
        updateReadyToInstallBody = "The update has been downloaded. Tap Install to apply it.",
        updateUpToDate = "You have the latest version",
        updateCheckFailed = "Update check failed",
        checkForUpdates = "Check for updates",
        updateButton = "Update",
        updateAvailableButton = "Update available",
        advisoryLabel = "Observation",
        areaOnlyLabel = "Area-level (no precise point)",
        cardSkullNote = "Skull (0–10) is a rough estimate — type, distance, reliability, sources. Not an official rating or a guarantee of your safety.",
        distanceLabel = "Distance",
        distanceToCityFormat = "Distance to %1\$s",
        etaLabel = "ETA",
        etaUnit = "min",
        approxNote = "All numbers in the app are approximate",
        pillDistanceCd = "Distance to %1\$s: %2\$d km",
        gpsOffLabel = "GPS off — no zone data",
        inRedZone = "In red zone",
        inYellowZone = "In yellow zone",
        outsideZones = "Outside alert zones",
        editZonesLabel = "Edit zones",
        alertsBellToggle = "Toggle alerts on/off",
        kmUnit = "km",
        meterUnit = "m",
        moreInfoLabel = "More info",
        offLabel = "OFF",
        allAlertsOffLabel = "All alerts are off",
        mapCenterLabel = "Map centre",
        followMeTitle = "Follow me",
        followMeDesc = "The map and zones follow your GPS position.",
        pinCityTitle = "Pin to a city",
        pinCityDesc = "The map centre and zones pin to the selected city. Cities with an official oblast alert are marked red.",
        mapPillPinned = "Pinned: %1\$s",
        alertBannerFormat = "%1\$s: alert",
        alertSourceBackup = " · backup source",
        alertSourceBoth = " · NEPTUN + backup source",
        notifBodyRegionFormat = "%1\$s region",
        notifStatusPinned = "Zones are pinned to a city",
        offlineStatusTitle = "Offline",
        offlineBodyFormat = "Offline for %1\$s — backup systems active but less reliable. Tap to retry.",
        offlineOfficialSirensLine = "Rely on official sirens.",
        offlineRetryAction = "Retry",
        offlineDurMinFormat = "%1\$d m",
        offlineChannelName = "Offline monitoring",
        offlineChannelDesc = "Notifications when the connection to the alert server is lost.",
        offlineUiFormat = "Offline for %1\$s",
        allClearTitle = "%1\$s: all clear",
        allClearText = "The official air-raid alert has ended. All quiet.",
        batteryTitle = "Keep alerts running",
        batteryBody = "Android may pause this app in the background to save battery. The app itself uses very little power — alerts stream in live and your location uses a low-power fix — so allowing unrestricted background use won't drain your phone, and alerts keep ringing. Safety first.",
        batteryAllowButton = "Allow in background",
        batteryGranted = "Unrestricted in background",
        cardSizeLabel = "Threat card size and detail",
        guideTitle = "Feature guide",
        guideSettingsButton = "Feature guide",
        guideCategoryMap = "Map",
        guideCategoryZones = "Zones & alerts",
        guideCategoryLocation = "Location",
        guideCategoryCards = "Threat cards",
        guideCategorySettings = "Settings",
        guideLiveTitle = "Live threat map",
        guideLiveSummary = "See every tracked threat moving across the whole country on a dark map.",
        guideLiveD1 = "Markers show all 8 threat types — drones, missiles, guided bombs and more.",
        guideLiveD2 = "During an alert the map widens so you can check other regions at a glance.",
        guideLiveD3 = "Tap a marker to open its detail card; tap empty map to close it.",
        guideStripTitle = "Threat strip",
        guideStripSummary = "The strip at the bottom is a live scoreboard of threats by type.",
        guideStripD1 = "Only the types present right now appear — each tile shows its live count.",
        guideStripD2 = "A type with no threats is hidden; when nothing is around, the strip shows 'No threats'.",
        guideStripD3 = "A type disabled in Settings appears greyed out.",
        guideConnTitle = "Connection & scale",
        guideConnSummary = "The top pill shows your link to the alert server; the bar shows distance.",
        guideConnD1 = "Online means data is updating live; Offline warns data may be stale.",
        guideConnD2 = "Tap the pill to see server status and the NEPTUN attribution.",
        guideConnD3 = "The scale bar in the corner gives you real distances on the map.",
        guideZonesTitle = "Red & yellow zones",
        guideZonesSummary = "Two safety rings around you — urgent red and warning yellow.",
        guideZonesD1 = "Red (1–5 km): a threat here means a siren and red banner.",
        guideZonesD2 = "Yellow (6–20 km): a threat here means a warning chime and amber banner.",
        guideZonesD3 = "Tap a zone button on the map to zoom straight to it.",
        guideEditZonesTitle = "Edit zones",
        guideEditZonesSummary = "Fine-tune each zone's radius and mute alerts per zone.",
        guideEditZonesD1 = "Sliders change the circles on the map live.",
        guideEditZonesD2 = "Tap the bell to arm or mute a zone's alerts.",
        guideEditZonesD3 = "Changes apply immediately and stay saved.",
        guideNotifTitle = "Notifications",
        guideNotifSummary = "The app keeps listening in the background and sounds zone alerts.",
        guideNotifD1 = "Red zone → siren; yellow zone → chime; official oblast alert → its own sound.",
        guideNotifD2 = "A quiet status notification shows monitoring is running.",
        guideNotifD3 = "Your phone stays monitored even when the app is closed.",
        guideFastTitle = "Alert toggles",
        guideFastSummary = "Two switches control how aggressive alerts are.",
        guideFastD1 = "Fast objects sooner: missiles sound the siren the moment they cross any zone edge.",
        guideFastD2 = "Official alerts: adds the oblast air-raid signal on top.",
        guideFastD3 = "Both live in Settings → Alerts.",
        guideFollowTitle = "Follow me",
        guideFollowSummary = "The map and both zones follow your GPS position.",
        guideFollowD1 = "Your position shows as a glowing blue dot.",
        guideFollowD2 = "Zones move with you, so you always know if a threat is near.",
        guideFollowD3 = "Toggle it in Settings → Map centre.",
        guidePinTitle = "Pin to a city",
        guidePinSummary = "Fix the map and zones on a chosen city instead of your GPS.",
        guidePinD1 = "Useful when you're watching over family elsewhere.",
        guidePinD2 = "Distance on threat cards is measured to that city, not to you.",
        guidePinD3 = "Cities with an official alert are marked red in the list.",
        guideCardSizeTitle = "Card sizes",
        guideCardSizeSummary = "Three sizes control how much each threat card shows.",
        guideCardSizeD1 = "Small — one line: skull, type and ETA.",
        guideCardSizeD2 = "Medium — adds distance, speed and reliability.",
        guideCardSizeD3 = "Large — everything, including course and precision.",
        guideCardReadTitle = "Reading a card",
        guideCardReadSummary = "A threat card is a quick dossier on one object.",
        guideCardReadD1 = "The skull gauge (0–10) is a rough threat level.",
        guideCardReadD2 = "Distance and ETA are computed from your position (or pinned city).",
        guideCardReadD3 = "Speed, wave size, reliability, precision and age make up the rest.",
        guideLangTitle = "Language",
        guideLangSummary = "Switch between Ukrainian and English anytime.",
        guideLangD1 = "Two flags at the top of Settings.",
        guideLangD2 = "Applies everywhere — map, cards, notifications, this guide.",
        guideLangD3 = "Your choice is remembered on next launches.",
        guideTogglesTitle = "Threat toggles",
        guideTogglesSummary = "Each of the 8 threat types has separate Map and Alerts controls.",
        guideTogglesD1 = "Turning off Map hides the type and silences its alerts. Turning off Alerts keeps it on the map, but dimmed.",
        guideTogglesD2 = "A type with Alerts or Map off is hidden from the threat strip.",
        guideTogglesD3 = "Each card has details, typical speed and a wiki photo.",
        guideUpdateTitle = "Updates",
        guideUpdateSummary = "The app checks daily and can update itself.",
        guideUpdateD1 = "A new version shows a What's new note.",
        guideUpdateD2 = "Download and install straight from the dialog.",
        guideUpdateD3 = "You can also tap Check for updates in Settings.",
    )
}

/**
 * Pluralized "source(s)" word for the given count, per language.
 * English: 1 "source" / N "sources". Ukrainian: 1 "джерело" (21, 31…),
 * 2–4 "джерела" (22–24…), else "джерел" (5–20, 25–30…).
 */
fun sourcesWord(count: Int, lang: AppLanguage): String = when (lang) {
    AppLanguage.EN -> if (count == 1) "source" else "sources"
    AppLanguage.UA -> {
        val n10 = count % 10
        val n100 = count % 100
        when {
            n10 == 1 && n100 != 11 -> "джерело"
            n10 in 2..4 && n100 !in 12..14 -> "джерела"
            else -> "джерел"
        }
    }
}

/** Formats elapsed time since a threat's last fix as `m:ss` (e.g. 3:47, 0:05). */
fun formatElapsedMss(updatedAtMillis: Long?, nowMillis: Long): String {
    if (updatedAtMillis == null) return "–"
    val secs = ((nowMillis - updatedAtMillis) / 1000).coerceAtLeast(0)
    return "%d:%02d".format(secs / 60, secs % 60)
}

/** Formats a relative time string like NEPTUN's "2 J. 4 minutes ago" pattern, simplified. */
fun formatRelativeTime(updatedAtIso: String?, lang: AppLanguage): String {
    if (updatedAtIso.isNullOrBlank()) return Strings.get(lang).justNow
    return try {
        val then = java.time.Instant.parse(updatedAtIso)
        val now = java.time.Instant.now()
        val minutes = java.time.Duration.between(then, now).toMinutes()
        val s = Strings.get(lang)
        when {
            minutes < 1 -> s.justNow
            minutes < 60 -> "$minutes ${s.minutesAgoSuffix}"
            minutes < 60 * 24 -> {
                val h = minutes / 60
                val m = minutes % 60
                if (m == 0L) "$h ${s.hoursAgoSuffix}" else String.format(s.mixedTimeFormat, h, m)
            }
            else -> {
                val d = minutes / (60 * 24)
                val h = (minutes % (60 * 24)) / 60
                if (h == 0L) "$d ${s.daysAgoSuffix}" else String.format(s.mixedTimeFormat, d, h)
            }
        }
    } catch (e: Exception) {
        Strings.get(lang).justNow
    }
}
