package ua.ukrainedrones

/** Shared builder for a default active Threat so tests stay short. */
fun threat(
    id: String = "t1",
    type: ThreatType = ThreatType.SHAHED,
    title: String = "",
    region: String? = "Одеська",
    district: String? = null,
    locality: String? = null,
    lat: Double = 46.48,
    lon: Double = 30.73,
    heading: Double? = null,
    bearingDeg: Double? = null,
    status: String = "active",
    advisory: Boolean = false,
    areaOnly: Boolean = false,
    confirmations: Int = 1,
    reliability: Reliability = Reliability.MEDIUM,
    count: Int = 0,
    explanationShort: String? = null,
    speedKmh: Double? = null,
    uncertaintyKm: Double? = null,
    positionQuality: String? = "confirmed",
    confirmedAt: String? = null,
    confirmedAtMillis: Long? = null,
    updatedAt: String? = null,
    updatedAtMillis: Long? = null,
    trail: List<TrailPoint> = emptyList()
): Threat = Threat(
    id = id,
    type = type,
    title = title,
    region = region,
    district = district,
    locality = locality,
    lat = lat,
    lon = lon,
    heading = heading,
    bearingDeg = bearingDeg,
    status = status,
    advisory = advisory,
    areaOnly = areaOnly,
    confirmations = confirmations,
    reliability = reliability,
    count = count,
    explanationShort = explanationShort,
    speedKmh = speedKmh,
    uncertaintyKm = uncertaintyKm,
    positionQuality = positionQuality,
    confirmedAt = confirmedAt,
    confirmedAtMillis = confirmedAtMillis,
    updatedAt = updatedAt,
    updatedAtMillis = updatedAtMillis,
    trail = trail
)